### ISSUE TITLE
号多了会报错。

### ISSUE THREAD

**Issue by a1126065424** [lanzeweie/aolaxing#3]
**我20多个号。运行一半就会报错。**
用户：13136112341
当前积分：13 总共获得积分：13
总签到：1 天
首次获得用户信息
Traceback (most recent call last):
  File "/ql/data/scripts/lanzeweie_aolaxing/QLaolastart.py", line 171, in <module>
    contents = aola.zhu()
  File "/ql/data/scripts/lanzeweie_aolaxing/QLaolastart.py", line 135, in zhu
    Send_zhong = (aola.start(Cookie_list))
  File "/ql/data/scripts/lanzeweie_aolaxing/QLaolastart.py", line 102, in start
    credit,creditHistory,phoneNum,signInTotal,jsonResultname  = aola.user()
  File "/ql/data/scripts/lanzeweie_aolaxing/QLaolastart.py", line 40, in user
    user = requests.get(url,headers=hand)
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 575, in request
    prep = self.prepare_request(req)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 486, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 369, in prepare
    self.prepare_headers(headers)
  File "/usr/local/lib/python3.10/sit

**Comment by lanzeweie** [comment]
我没有多个账号来进行测试，等后续有空了修复吧，好像遇到cookie失效或者是不正确的，会自动结束

**Comment by lanzeweie** [comment]
早就解决了，忘记关帖子了
